/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const autoTable: typeof import('jspdf-autotable')['autoTable']
  const jsPDF: typeof import('jspdf')['jsPDF']
}
