const bitesdata = [
    {course_id: "1",
        name:"The Rise of Tokens on Bitcoin",
        description:"Ordinals and Inscriptions, BCR20, Stamps and Runes. Learn how and why tokens on Bitcoin are growing in popularity",
        category:"Intermediate",
        subcategory:"Bitcoin",
        image_url:"https://s3.us-east-1.amazonaws.com/contents.newzenler.com/24209/library/bitcoin-bite666c1e754a220_lg.png",
        sponsor_name:"A Block of Crypto",
        sponsor_img: "https://s3.us-east-1.amazonaws.com/contents.newzenler.com/24209/library/logo-small645568781ad00.png",
        points:"Learning Points 500 ",
        courselink:"https://www.ablockofcrypto.com/courses/tokens-on-bitcoin"   
    },
    {course_id: "2",
        name:"Web3 Wallet Security: From Private Keys to Public Addresses",
        description:"learn about XXXX",
        category:"Essentials",
        subcategory:"wallets",
        image_url:"https://s3.us-east-1.amazonaws.com/contents.newzenler.com/24209/library/bitcoin-bite666c1e754a220_lg.png",
        sponsor_name:"A Block of Crypto",
        sponsor_img: "https://s3.us-east-1.amazonaws.com/contents.newzenler.com/24209/library/logo-small645568781ad00.png" ,
        points:"Learning Points 500 ",
        courselink:"https://www.ablockofcrypto.com/courses/web3-wallet-security"

    },
    {course_id: "3",
        name:"Exploring Web3: Unlocking Business Potential in Blockchain",    
        description:"learn about XXXX", 
        category:"Essentials",
        subcategory:"wallets",
        image_url:"https://s3.us-east-1.amazonaws.com/contents.newzenler.com/24209/library/web365b2516e66f67_lg.png",
        sponsor_name:"A Block of Crypto",
        sponsor_img: "https://s3.us-east-1.amazonaws.com/contents.newzenler.com/24209/library/logo-small645568781ad00.png" ,
        points:"Learning Points 500 " ,
        courselink:"https://www.ablockofcrypto.com/courses/tokens-on-bitcoin"  
    },
    {course_id: "4",
        name:"Introduction to Leverage in DeFi for Wealth Growth",
        description:"learn about XXXX",
        category:"intermediate",
        subcategory:"Defi",
        image_url:"https://s3.us-east-1.amazonaws.com/contents.newzenler.com/24209/library/leverage65b22dc6eca92_lg.png",
        sponsor_name:"A Block of Crypto",
        sponsor_img: "https://s3.us-east-1.amazonaws.com/contents.newzenler.com/24209/library/logo-small645568781ad00.png",
        points:"Learning Points 500 " ,
        courselink:"https://www.ablockofcrypto.com/courses/tokens-on-bitcoin"     
    },
    {course_id: "5",
        name:"The Power of Compound Interest - Financial Literacy Skills For DeFi",
        description:"learn about XXXX",
        category:"Beginner",
        subcategory:"Defi",
        image_url:"https://s3.us-east-1.amazonaws.com/contents.newzenler.com/24209/library/compound65b250d589970_lg.png",
        sponsor_name:"A Block of Crypto",
        sponsor_img: "https://s3.us-east-1.amazonaws.com/contents.newzenler.com/24209/library/logo-small645568781ad00.png" ,
        points:"Learning Points 500 ",  
        courselink:"https://www.ablockofcrypto.com/courses/tokens-on-bitcoin",   
    },
]

export default bitesdata

